on: push
name: Build FFmpeg

jobs:
  build-osx:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build
        run: ${GITHUB_WORKSPACE}/scripts/osx/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: osx-${{ matrix.arch }}
          path: ${GITHUB_WORKSPACE}/build-${{ matrix.arch }}

  build-win:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - win-x86
          - win-x64
          - win-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make nasm gcc mingw-w64

      - name: Build
        run: ${GITHUB_WORKSPACE}/scripts/win/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-${{ matrix.arch }}
          path: ${GITHUB_WORKSPACE}/build-${{ matrix.arch }}