on: push
name: Build FFmpeg

jobs:
  build-osx:
    name: Build (OSX)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build (x86_64)
        run: ${GITHUB_WORKSPACE}/scripts/osx/fetch_and_build.sh
        env:
          arch: x86_64

      - name: Build (arm64)
        run: ${GITHUB_WORKSPACE}/scripts/osx/fetch_and_build.sh
        env:
          arch: arm64

      - name: Combine
        run: ${GITHUB_WORKSPACE}/scripts/osx/combine_universal.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-osx
          path: ${GITHUB_WORKSPACE}/artifacts/