on: push
name: Build FFmpeg

jobs:
  build-osx:
    name: Build OSX
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build
        run: ${{ github.workspace }}/scripts/osx/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: osx-${{ matrix.arch }}
          path: ${{ github.workspace }}/build-${{ matrix.arch }}

  combine-osx:
    name: Combine OSX libs
    runs-on: macos-latest
    needs: build-osx
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: osx-x86_64
      - uses: actions/download-artifact@v3
        with:
          name: osx-arm64

      - name: Combine
        run: ${{ github.workspace }}/scripts/osx/combine_universal.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: osx
          path: ${{ github.workspace }}/artifacts

  build-win:
    name: Build Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make nasm gcc mingw-w64

      - name: Build
        run: ${{ github.workspace }}/scripts/win/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-${{ matrix.arch }}
          path: ${{ github.workspace }}/build-${{ matrix.arch }}

  build-win-arm64:
    name: Build Windows (arm64)
    runs-on: ubuntu-latest
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: scripts/win/fetch_and_build.sh
        env:
          arch: arm64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-arm64
          path: build-arm64